### ISSUE TITLE
Permissions issue when trying to select answer from adaptive card

### ISSUE THREAD

**Issue by phil-bevan** [unsw-edu-au/QBot#38]
![image](https://user-images.githubusercontent.com/48096014/94171127-cad22b00-fe88-11ea-9869-236458eacf92.png)
![image](https://user-images.githubusercontent.com/48096014/94171189-e0dfeb80-fe88-11ea-8eb3-3848726a367b.png)

System.ArgumentNullException: Value cannot be null. Parameter name: source at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate) at 
Microsoft.Teams.Apps.QBot.Bot.MessagesController.<GetAllReplies>d__8.MoveNext() in D:\home\site\repository\Source\Microsoft.Teams.Apps.QBot.Bot\Controllers\MessagesController.cs:line 704
 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Teams.Apps.QBot.Bot.MessagesController.<HandleSelectAnswerFromCard>d__4.MoveNext() in D:\home\site\repository\Source\Microsoft.Teams.Apps.QBot.Bot\Controllers\MessagesController.cs:line 382
 --- End of stack trace from previous location where exception was thrown --- at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Teams.Apps.QBot.Bot.MessagesController.<HandleInvokeMessages>d__1.MoveNext() in D:\home\site\repository\Source\Microsoft.Teams.Apps.QBot.Bot\Controllers\MessagesController.cs:line 71
 --- End of stack trace from previous location where exception was thrown --- at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.Teams.Apps.QBot.Bot.MessagesController.<Post>d__0.MoveNext() in D:\home\site\repository\Source\Microsoft.Teams.Apps.QBot.Bot\Controllers\MessagesController.cs:line 53

The Graph call that fails comes from:
string endpoint = ServiceHelper.GraphRootUri + @"/beta";
string queryParameter = "/teams/" + teamId + "/channels/" + channelId + "/messages/" + messageId + "/replies";

e.g. https://graph.microsoft.com/beta/teams/0c954098-ee6f-4559-b08b-3cf965b6e9b4/channels/19:5a399d41c95b4e469ff0ae4c20dcfb45@thread.tacv2/messages/1600957992560/replies

Logging in to Graph Explorer as my service user and executing the above also returns 403 but also informs me that I have no missing permissions to make this call! (I have added the required User.Read.All and Group.ReadWrite.All, and am a member of the Team).  Executing the same call as System Admin works fine.

**Comment by shortboard** [comment]
I'm gleaning from your question that you are using delegated permissions for the bot. Have you provided admin consent to the Group.ReadWrite.All and User.Read.All? I believe from your question you indicated that you have already checked that the service account is a member of the team but i'd suggest removing and adding the service account back.

If you are using application permissions for the bot you'll find the replies endpoint is actually a [protected api](https://docs.microsoft.com/en-us/graph/teams-protected-apis) and you'll need to fill out [this form](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR1ax4zKyZjVBmutzKVo1pVtUQ1VJMlNTNUdJV1FKTzVZSVU4MlMwTTdOTSQlQCN0PWcu) to gain access to it.

**Comment by phil-bevan** [comment]
This is now resolved.  I was using Delegated permissions, and although the service account was a member of the team, I believe the issue was that it did not have a valid Teams license.  After manually signing in to Teams as the Service Account the issue is resolved.
