### ISSUE TITLE
Dashboard keeps asking to "sign in to continue"

### ISSUE THREAD

**Issue by jfbillette** [unsw-edu-au/QBot#42]
Hello. It seems we were able to complete our deployment of this application in our environment. We do have a strange issue with using the bot from Teams. We get to the Dashboard tab with a request to sign in. We do without errors, but we do not get to the next screen or functionality. We can keep doing a sign in, but that is pretty much it. 

We have rechecked the configuration and options, and I am sure we are just missing a small detail to get this to work. Has anyone encountered this issue before? 

Thank you.

**Comment by TimB87** [comment]
I _think_ we had this problem over here too. Did you do the manual deployment or via script? 
If per script, you didn't get any error on the deployment process?

**Comment by jfbillette** [comment]
I went with the template. But as mentioned in a different issue, I had a failure with the question app part of the template deployment. I was although able to use the deployment center in that app service to redeploy the code successfully. It did look like everything had completed after checking all the resources.

If that is related, i guess my only other option would the manual deployment. I was kind of hoping it would be something relatively simple versus having to start over.

**Comment by TimB87** [comment]
We tried the manual deployment method and it didn't work for the same reasons. I wish I could show some data about it but it's already deleted from our azure tenant (because you don't want to pay container fees for something that's not working, right?).

**Comment by jfbillette** [comment]
Hi. I was able to get the solution deployed using the manual process. the Template/script install just did not work for me. 

Thank you for your input.

**Comment by TimB87** [comment]
Interesting news though @jfbillette, thanks for reporting. I am sure this is an obvious yes, but you did follow the manual deployment guide without any additional, undocumented steps? #41 is still an issue for you though?

**Comment by jfbillette** [comment]
We followed the steps as is. Although, you have to make sure the ID tokens checkbox is selected in the authentication section of the "QBot API Auth App Registration" APP registration. I double checked again and I could not find it in the manual deployment guide. 

As far as I know, we only have issue #41 left to resolve.

**Comment by TimB87** [comment]
Thanks, we will have to try again with the manual deployment and see if we can reach #41 (again, we had it like that once)
